### ISSUE TITLE
SmiteshP/nvim-navic ugly background

### ISSUE THREAD

**Issue by azzamsa** [miikanissi/modus-themes.nvim#41]
### Description

Hi, 

I get this ugly background in SmiteshP/nvim-navic.

- Modus

![image](https://github.com/user-attachments/assets/f87e003c-131b-46f8-a020-f7fe3135ee36)

- Tokyonight

![image](https://github.com/user-attachments/assets/1d3e12a5-24a0-4f99-af8a-483f545f12a2)

### Neovim version

```markdown
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
```

### Terminal and multiplexer

neovide 0.13.3

### Modus themes version

a702bfb

### Steps to reproduce

```lua
    {
        "LunarVim/breadcrumbs.nvim",
        config = function()
            require("breadcrumbs").setup()
        end,
        dependencies = {
            "SmiteshP/nvim-navic",
            config = function()
                require("nvim-navic").setup({
                    icons = Icons.kind,
                    highlight = true,
                    lsp = {
                        auto_attach = true,
                    },
                    click = true,
                    separator = " " .. Icons.ui.ChevronRight .. " ",
                    depth_limit = 0,
                    depth_limit_indicator = "..",
                })
            end,
        },
    },
```

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "miikanissi/modus-themes.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("modus")
-- add anything else here
```

**Comment by miikanissi** [comment]
Hi,

I looked into this and the reason this happens is due to the `WinBarNC` highlight group being different from the `WinBar` highlight group and Navic doesn't support an active vs inactive background value. 

There is an issue raised for Navic here about this: https://github.com/SmiteshP/nvim-navic/issues/146 

There isn't a way to fix this via the theme except to make both `WinBar` and `WinBarNC` use the same background color. At the moment I don't plan on changing this as I think the inactive and active winbars should have a different background. 

In order to "fix" this for yourself you can set the background color of `WinBarNC` as follows:

```lua
	{
		"miikanissi/modus-themes.nvim",
		priority = 1000,
		config = function()
			require("modus-themes").setup({
				on_highlights = function(highlights, colors)
					highlights.WinBarNC = { bg = colors.bg_tab_current }
				end,
			})

			vim.cmd.colorscheme("modus")
		end,
	},
```

**Comment by azzamsa** [comment]
Thank you so much for taking the time to look into this issue. This theme is one of the reasons I felt comfortable switching from Emacs. Thanks again! 🥞
